[package]
name = "rcalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "staticlib"]


[dependencies]
cxx = "1.0.109"

[build-dependencies]
cxx-build = "1.0.109"
